shell = "zsh"

[plugins."zsh-users/zsh-completions"]
github = "zsh-users/zsh-completions"

[plugins."zsh-users/zsh-syntax-highlighting"]
github = "zsh-users/zsh-syntax-highlighting"

[plugins."zsh-users/zsh-history-substring-search"]
github = "zsh-users/zsh-history-substring-search"

[plugins."zsh-users/zsh-history-substring-search".hooks]
post = """
  bindkey '^[[A' history-substring-search-up
  bindkey '^[[B' history-substring-search-down
"""

[plugins."zsh-users/zsh-autosuggestions"]
github = "zsh-users/zsh-autosuggestions"
