shell = "zsh"

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"

[plugins.zsh-vi-mode.hooks]
pre = """
  ZVM_INIT_MODE=sourcing
"""

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.compinit]
inline = """
  autoload -Uz compinit && compinit
  autoload -Uz bashcompinit && bashcompinit
"""

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.fzf-tab.hooks]
post = """
  zstyle ':fzf-tab:*' use-fzf-default-opts yes
  zstyle ':fzf-tab:*' fzf-pad 5
  (( ! $+commands[fzf] )) && disable-fzf-tab
"""

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.zsh-history-substring-search.hooks]
post = """
  bindkey '^[[A' history-substring-search-up
  bindkey '^[[B' history-substring-search-down
"""
