flatpak = [
  "com.google.Chrome",
  "com.spotify.Client",
  "com.usebottles.bottles",
  "com.valvesoftware.Steam",
  "org.freedesktop.Platform.VulkanLayer.MangoHud",
  "org.freedesktop.Platform.VulkanLayer.OBSVkCapture",
  "org.freedesktop.Platform.VulkanLayer.gamescope",
  "org.freedesktop.Platform.VulkanLayer.vkBasalt",
  "org.telegram.desktop",
]
