dnf = ["android-tools"]

brew = [
  "bat",
  "eza",
  "fastfetch",
  "gh",
  "git-delta",
  "git-extras",
  "neovim",
  "p7zip",
  "proto",
  "ripgrep",
  "rustup",
  "sheldon",
  "shellcheck",
  "shfmt",
  "starship",
  "stylua",
  "taplo",
  "unar",
  "vcsh",
  "zig",
]
