dnf = [
  "@development-tools",
  "android-tools",
  "dconf",
  "fish",
  "host-spawn",
  "openssl-devel",      # For cargo:cargo-update
  "starship",
  "wl-clipboard",
]

cargo = ["cargo-update", "metapac"]
