plugins:
  - inline
  - discogs
per_disc_numbering: true
item_fields:
  disc_and_track: f"{disc:02d}-{track:02d}" if disctotal > 1 else f"{track:02d}"
paths:
  default: $albumartist/$album%aunique{}/$disc_and_track. $title
  singleton: $artist/$title%sunique{}
  comp: Various Artists/$album%aunique{}/$disc_and_track. $title
